name: tfl_api_client
description: A starting point for Dart libraries or applications.
version: 0.4.0
homepage: https://github.com/tnc1997/dart-tfl-api-client
author: Thomas Clark

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  http: ^0.12.0
  json_annotation: ^3.0.0

dev_dependencies:
  build_runner: ^1.0.0
  dotenv: ^2.0.0
  json_serializable: ^3.0.0
  pedantic: ^1.0.0
  test: ^1.0.0
